<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../Modules/Catalog/Vaulta.Catalog.Contracts/Vaulta.Catalog.Contracts.csproj" />
    <ProjectReference Include="../Modules/Collection/Vaulta.Collection.Contracts/Vaulta.Collection.Contracts.csproj" />
    <ProjectReference Include="../Modules/Assets/Vaulta.Assets.Contracts/Vaulta.Assets.Contracts.csproj" />
    <ProjectReference Include="../Modules/Marketplace/Vaulta.Marketplace.Contracts/Vaulta.Marketplace.Contracts.csproj" />
    <ProjectReference Include="../Modules/Orders/Vaulta.Orders.Contracts/Vaulta.Orders.Contracts.csproj" />
    <ProjectReference Include="../Modules/Payments/Vaulta.Payments.Contracts/Vaulta.Payments.Contracts.csproj" />
    <ProjectReference Include="../Modules/Wallets/Vaulta.Wallets.Contracts/Vaulta.Wallets.Contracts.csproj" />
  </ItemGroup>
</Project>