using Npgsql;
using Testcontainers.PostgreSql;

namespace Vaulta.Identity.IntegrationTests;

/// <summary>A fresh migration database, in Docker or the explicitly supplied isolated test server.</summary>
internal sealed class TestPostgresDatabase : IAsyncDisposable
{
    private PostgreSqlContainer? _container;
    private string? _adminConnection;
    private string? _database;
    public string ConnectionString { get; private set; } = null!;

    public static async Task<TestPostgresDatabase> Start()
    {
        var lease = new TestPostgresDatabase();
        var supplied = Environment.GetEnvironmentVariable("VAULTA_TEST_POSTGRES");
        if (string.IsNullOrWhiteSpace(supplied))
        {
            lease._container = new PostgreSqlBuilder("postgres:17-alpine").Build();
            await lease._container.StartAsync(); lease.ConnectionString = lease._container.GetConnectionString();
        }
        else
        {
            var connection = new NpgsqlConnectionStringBuilder(supplied) { Database = "postgres" };
            lease._adminConnection = connection.ConnectionString;
            lease._database = "vaulta_migration_" + Guid.NewGuid().ToString("N");
            await using var admin = new NpgsqlConnection(lease._adminConnection); await admin.OpenAsync();
            await using var create = new NpgsqlCommand($"CREATE DATABASE \"{lease._database}\"", admin);
            await create.ExecuteNonQueryAsync();
            connection.Database = lease._database; lease.ConnectionString = connection.ConnectionString;
        }
        return lease;
    }

    public async ValueTask DisposeAsync()
    {
        if (_container is not null) { await _container.DisposeAsync(); return; }
        if (_database is null || _adminConnection is null) return;
        // The name is generated by this lease; never drop the caller's supplied database.
        await using var admin = new NpgsqlConnection(_adminConnection); await admin.OpenAsync();
        await using var drop = new NpgsqlCommand($"DROP DATABASE IF EXISTS \"{_database}\" WITH (FORCE)", admin);
        await drop.ExecuteNonQueryAsync();
    }
}
