<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <ProjectReference Include="../Vaulta.Payments.Application/Vaulta.Payments.Application.csproj" />
    <ProjectReference Include="../../../Vaulta.SharedKernel/Vaulta.SharedKernel.csproj" />
    <ProjectReference Include="../../Orders/Vaulta.Orders.Application/Vaulta.Orders.Application.csproj" />
    <ProjectReference Include="../../Identity/Vaulta.Identity.Application/Vaulta.Identity.Application.csproj" />
    <FrameworkReference Include="Microsoft.AspNetCore.App" />
    <PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.6" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.6"><PrivateAssets>all</PrivateAssets></PackageReference>
  </ItemGroup>
</Project>