// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vaulta.Collection.Infrastructure;

#nullable disable

namespace Vaulta.Collection.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CollectionDbContext))]
    [Migration("20261001175706_TrackListingOwnership")]
    partial class TrackListingOwnership
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("collection")
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Vaulta.Collection.Domain.CollectibleItem", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal?>("AcquisitionAmount")
                        .HasPrecision(18, 4)
                        .HasColumnType("numeric(18,4)")
                        .HasColumnName("acquisition_amount");

                    b.Property<string>("AcquisitionCurrency")
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("acquisition_currency");

                    b.Property<DateOnly?>("AcquisitionDate")
                        .HasColumnType("date")
                        .HasColumnName("acquisition_date");

                    b.Property<Guid>("CollectionEntryId")
                        .HasColumnType("uuid")
                        .HasColumnName("collection_entry_id");

                    b.Property<string>("Condition")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("condition");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid?>("ListedById")
                        .HasColumnType("uuid")
                        .HasColumnName("listed_by_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("notes");

                    b.Property<DateTimeOffset?>("RemovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("removed_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid>("Version")
                        .IsConcurrencyToken()
                        .HasColumnType("uuid")
                        .HasColumnName("version");

                    b.HasKey("Id");

                    b.HasIndex("CollectionEntryId", "Status")
                        .HasDatabaseName("ix_collection_items_entry_status");

                    b.HasIndex("CollectionEntryId", "UserId");

                    b.HasIndex("UserId", "Condition", "Status")
                        .HasDatabaseName("ix_collection_items_user_condition_status");

                    b.HasIndex("UserId", "Status", "CreatedAt")
                        .HasDatabaseName("ix_collection_items_user_status_created");

                    b.ToTable("collectible_items", "collection");
                });

            modelBuilder.Entity("Vaulta.Collection.Domain.CollectibleItemAsset", b =>
                {
                    b.Property<Guid>("CollectibleItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("collectible_item_id");

                    b.Property<Guid>("AssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("asset_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsPrimary")
                        .HasColumnType("boolean")
                        .HasColumnName("is_primary");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("type");

                    b.HasKey("CollectibleItemId", "AssetId");

                    b.HasIndex("AssetId")
                        .IsUnique()
                        .HasDatabaseName("ux_collection_item_asset_asset");

                    b.HasIndex("CollectibleItemId", "IsPrimary")
                        .IsUnique()
                        .HasDatabaseName("ux_collection_item_asset_primary")
                        .HasFilter("is_primary = true");

                    b.HasIndex("CollectibleItemId", "SortOrder")
                        .HasDatabaseName("ix_collection_item_assets_order");

                    b.ToTable("collectible_item_assets", "collection");
                });

            modelBuilder.Entity("Vaulta.Collection.Domain.CollectionEntry", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("PrintingId")
                        .HasColumnType("uuid")
                        .HasColumnName("printing_id");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.Property<Guid?>("VariantId")
                        .HasColumnType("uuid")
                        .HasColumnName("variant_id");

                    b.HasKey("Id");

                    b.HasAlternateKey("Id", "UserId")
                        .HasName("ak_collection_entries_id_user");

                    b.HasIndex("UserId", "CreatedAt")
                        .HasDatabaseName("ix_collection_entries_user_created");

                    b.HasIndex("UserId", "PrintingId")
                        .IsUnique()
                        .HasDatabaseName("ux_collection_entries_user_printing_no_variant")
                        .HasFilter("variant_id IS NULL");

                    b.HasIndex("UserId", "PrintingId", "VariantId")
                        .IsUnique()
                        .HasDatabaseName("ux_collection_entries_user_printing_variant")
                        .HasFilter("variant_id IS NOT NULL");

                    b.ToTable("collection_entries", "collection");
                });

            modelBuilder.Entity("Vaulta.Collection.Domain.ItemOwnershipTransfer", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("BuyerId")
                        .HasColumnType("uuid")
                        .HasColumnName("buyer_id");

                    b.Property<Guid>("BuyerItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("buyer_item_id");

                    b.Property<Guid>("ListingId")
                        .HasColumnType("uuid")
                        .HasColumnName("listing_id");

                    b.Property<decimal>("PriceBrl")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("price_brl");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("received_at");

                    b.Property<Guid>("SellerId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_id");

                    b.Property<Guid>("SellerItemId")
                        .HasColumnType("uuid")
                        .HasColumnName("seller_item_id");

                    b.HasKey("OrderId");

                    b.HasIndex("BuyerItemId")
                        .IsUnique()
                        .HasDatabaseName("ux_collection_transfer_buyer_item");

                    b.HasIndex("SellerItemId")
                        .IsUnique()
                        .HasDatabaseName("ux_collection_transfer_seller_item");

                    b.ToTable("item_ownership_transfers", "collection");
                });

            modelBuilder.Entity("Vaulta.Collection.Infrastructure.CollectionIdempotencyKey", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("IdempotencyKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("idempotency_key");

                    b.Property<string>("Operation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("operation");

                    b.Property<string>("RequestHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("request_hash");

                    b.Property<string>("ResponsePayload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("response_payload");

                    b.Property<int>("ResponseStatus")
                        .HasColumnType("integer")
                        .HasColumnName("response_status");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid")
                        .HasColumnName("user_id");

                    b.HasKey("Id");

                    b.HasIndex("UserId", "Operation", "IdempotencyKey")
                        .IsUnique()
                        .HasDatabaseName("ux_collection_idempotency_keys_user_operation_key");

                    b.ToTable("idempotency_keys", "collection");
                });

            modelBuilder.Entity("Vaulta.SharedKernel.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.ToTable("outbox_messages", "identity", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Vaulta.Collection.Domain.CollectibleItem", b =>
                {
                    b.HasOne("Vaulta.Collection.Domain.CollectionEntry", null)
                        .WithMany()
                        .HasForeignKey("CollectionEntryId", "UserId")
                        .HasPrincipalKey("Id", "UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Vaulta.Collection.Domain.CollectibleItemAsset", b =>
                {
                    b.HasOne("Vaulta.Collection.Domain.CollectibleItem", null)
                        .WithMany("Assets")
                        .HasForeignKey("CollectibleItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Vaulta.Collection.Domain.ItemOwnershipTransfer", b =>
                {
                    b.HasOne("Vaulta.Collection.Domain.CollectibleItem", null)
                        .WithMany()
                        .HasForeignKey("BuyerItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vaulta.Collection.Domain.CollectibleItem", null)
                        .WithMany()
                        .HasForeignKey("SellerItemId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Vaulta.Collection.Domain.CollectibleItem", b =>
                {
                    b.Navigation("Assets");
                });
#pragma warning restore 612, 618
        }
    }
}
