<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <InternalsVisibleTo Include="Vaulta.Identity.UnitTests" />
    <InternalsVisibleTo Include="Vaulta.Identity.IntegrationTests" />
    <PackageReference Include="AWSSDK.BedrockRuntime" Version="4.0.101.7" />
	<ProjectReference Include="../Vaulta.Catalog.Application/Vaulta.Catalog.Application.csproj" />
	<ProjectReference Include="../../../Vaulta.SharedKernel/Vaulta.SharedKernel.csproj" />
	<FrameworkReference Include="Microsoft.AspNetCore.App" />
	<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="10.0.0" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="10.0.6" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.6"><PrivateAssets>all</PrivateAssets></PackageReference>
		<PackageReference Include="Tesseract" Version="5.2.0" />
		<PackageReference Include="SixLabors.ImageSharp" Version="3.1.12" />
		<PackageReference Include="FuzzySharp" Version="2.0.2" />
  </ItemGroup>
</Project>
