// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vaulta.Vision.Infrastructure;

#nullable disable

namespace Vaulta.Vision.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(VisionDbContext))]
    [Migration("20261003122222_VisualReferences")]
    partial class VisualReferences
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("vision")
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Vaulta.Vision.Domain.VisualReference", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Dimension")
                        .HasColumnType("integer")
                        .HasColumnName("dimension");

                    b.Property<string>("ErrorCategory")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("error_category");

                    b.Property<string>("ImageSha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("image_sha256");

                    b.Property<string>("ModelManifestJson")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("model_manifest_json");

                    b.Property<string>("ModelVersion")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("model_version");

                    b.Property<string>("Origin")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("origin");

                    b.Property<string>("OriginalSourceSha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("original_source_sha256");

                    b.Property<Guid>("PrintingId")
                        .HasColumnType("uuid")
                        .HasColumnName("printing_id");

                    b.Property<Guid?>("SourceAssetId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_asset_id");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("status");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.PrimitiveCollection<float[]>("Vector")
                        .HasColumnType("real[]")
                        .HasColumnName("vector");

                    b.Property<string>("VectorSha256")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("vector_sha256");

                    b.HasKey("Id");

                    b.HasIndex("ModelVersion", "Status");

                    b.HasIndex("PrintingId", "ModelVersion", "SourceAssetId", "Origin")
                        .IsUnique();

                    b.ToTable("visual_references", "vision");
                });
#pragma warning restore 612, 618
        }
    }
}
