// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Vaulta.Catalog.Infrastructure;

#nullable disable

namespace Vaulta.Catalog.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CatalogDbContext))]
    [Migration("20261003032601_ScannerResearchedMarketSnapshots")]
    partial class ScannerResearchedMarketSnapshots
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("catalog")
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pg_trgm");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Vaulta.Catalog.Domain.Card", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<string>("ImageAssetKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("image_asset_key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_name");

                    b.Property<string>("RulesText")
                        .HasColumnType("text")
                        .HasColumnName("rules_text");

                    b.Property<string>("Subtypes")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("subtypes");

                    b.Property<string>("Supertype")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("supertype");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "NormalizedName")
                        .HasDatabaseName("ix_catalog_cards_game_name");

                    b.ToTable("cards", "catalog");
                });

            modelBuilder.Entity("Vaulta.Catalog.Domain.CatalogExternalId", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("content_hash");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("entity_id");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("entity_type");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("external_id");

                    b.Property<DateTimeOffset>("FirstSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("first_seen_at");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_seen_at");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("provider");

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("ix_catalog_external_ids_entity");

                    b.HasIndex("Provider", "EntityType", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ux_catalog_external_ids_source");

                    b.ToTable("external_ids", "catalog");
                });

            modelBuilder.Entity("Vaulta.Catalog.Domain.CatalogSyncRun", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<string>("ErrorCategory")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("error_category");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("provider");

                    b.Property<int>("RecordsCreated")
                        .HasColumnType("integer")
                        .HasColumnName("records_created");

                    b.Property<int>("RecordsRead")
                        .HasColumnType("integer")
                        .HasColumnName("records_read");

                    b.Property<int>("RecordsUnresolved")
                        .HasColumnType("integer")
                        .HasColumnName("records_unresolved");

                    b.Property<int>("RecordsUpdated")
                        .HasColumnType("integer")
                        .HasColumnName("records_updated");

                    b.Property<string>("Scope")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("scope");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("Provider", "StartedAt")
                        .HasDatabaseName("ix_catalog_sync_runs_provider_started");

                    b.ToTable("sync_runs", "catalog");
                });

            modelBuilder.Entity("Vaulta.Catalog.Domain.Game", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("character varying(32)")
                        .HasColumnName("code");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_catalog_games_code");

                    b.ToTable("games", "catalog");

                    b.HasData(
                        new
                        {
                            Id = new Guid("f18fd4d1-2514-4b19-9eaa-f33c04564c7b"),
                            Code = "pokemon",
                            Name = "Pokémon"
                        });
                });

            modelBuilder.Entity("Vaulta.Catalog.Domain.Printing", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("ArtworkProvider")
                        .HasMaxLength(40)
                        .HasColumnType("character varying(40)")
                        .HasColumnName("artwork_provider");

                    b.Property<Guid>("CardId")
                        .HasColumnType("uuid")
                        .HasColumnName("card_id");

                    b.Property<string>("CollectorNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("collector_number");

                    b.Property<string>("ExternalArtworkUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("character varying(2048)")
                        .HasColumnName("external_artwork_url");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Language")
                        .IsRequired()
                        .HasMaxLength(35)
                        .HasColumnType("character varying(35)")
                        .HasColumnName("language");

                    b.Property<string>("NormalizedCollectorNumber")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("normalized_collector_number");

                    b.Property<string>("Rarity")
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("rarity");

                    b.Property<string>("RawRarity")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("raw_rarity");

                    b.Property<Guid>("SetId")
                        .HasColumnType("uuid")
                        .HasColumnName("set_id");

                    b.HasKey("Id");

                    b.HasIndex("CardId")
                        .HasDatabaseName("ix_catalog_printings_card");

                    b.HasIndex("SetId", "IsActive")
                        .HasDatabaseName("ix_catalog_printings_set_active");

                    b.HasIndex("SetId", "NormalizedCollectorNumber", "Language")
                        .IsUnique()
                        .HasDatabaseName("ux_catalog_printings_set_number_language");

                    b.ToTable("printings", "catalog");
                });

            modelBuilder.Entity("Vaulta.Catalog.Domain.Series", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id");

                    b.HasIndex("GameId", "NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("ux_catalog_series_game_name");

                    b.ToTable("series", "catalog");
                });

            modelBuilder.Entity("Vaulta.Catalog.Domain.Set", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("code");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid")
                        .HasColumnName("game_id");

                    b.Property<string>("LogoAssetKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("logo_asset_key");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("normalized_name");

                    b.Property<string>("ReleaseDate")
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)")
                        .HasColumnName("release_date");

                    b.Property<Guid?>("SeriesId")
                        .HasColumnType("uuid")
                        .HasColumnName("series_id");

                    b.Property<string>("SymbolAssetKey")
                        .HasMaxLength(512)
                        .HasColumnType("character varying(512)")
                        .HasColumnName("symbol_asset_key");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId");

                    b.HasIndex("GameId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_catalog_sets_game_code")
                        .HasFilter("code IS NOT NULL");

                    b.HasIndex("GameId", "NormalizedName")
                        .HasDatabaseName("ix_catalog_sets_game_name");

                    b.ToTable("sets", "catalog");
                });

            modelBuilder.Entity("Vaulta.Catalog.Domain.Variant", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("character varying(80)")
                        .HasColumnName("code");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("name");

                    b.Property<Guid>("PrintingId")
                        .HasColumnType("uuid")
                        .HasColumnName("printing_id");

                    b.Property<string>("RawValue")
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("raw_value");

                    b.HasKey("Id");

                    b.HasIndex("PrintingId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ux_catalog_variants_printing_code");

                    b.ToTable("variants", "catalog");
                });

            modelBuilder.Entity("Vaulta.Catalog.Infrastructure.DailyCardMarketSnapshot", b =>
                {
                    b.Property<Guid>("PrintingId")
                        .HasColumnType("uuid")
                        .HasColumnName("printing_id");

                    b.Property<DateOnly>("MarketDay")
                        .HasColumnType("date")
                        .HasColumnName("market_day");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset>("RefreshAfter")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_after");

                    b.HasKey("PrintingId", "MarketDay");

                    b.ToTable("daily_card_market_snapshots", "catalog");
                });

            modelBuilder.Entity("Vaulta.Catalog.Infrastructure.MarketResearch.ScannerResearchSnapshot", b =>
                {
                    b.Property<string>("CacheKey")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("cache_key");

                    b.Property<DateTimeOffset>("FetchedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fetched_at");

                    b.Property<DateOnly>("MarketDay")
                        .HasColumnType("date")
                        .HasColumnName("market_day");

                    b.Property<string>("Outcome")
                        .IsRequired()
                        .HasMaxLength(24)
                        .HasColumnType("character varying(24)")
                        .HasColumnName("outcome");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset>("RefreshAfter")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_after");

                    b.HasKey("CacheKey");

                    b.HasIndex("RefreshAfter");

                    b.ToTable("scanner_research_snapshots", "catalog");
                });

            modelBuilder.Entity("Vaulta.SharedKernel.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Error")
                        .HasColumnType("text")
                        .HasColumnName("error");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload");

                    b.Property<DateTimeOffset?>("ProcessedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processed_at");

                    b.Property<int>("RetryCount")
                        .HasColumnType("integer")
                        .HasColumnName("retry_count");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt")
                        .HasFilter("processed_at IS NULL");

                    b.ToTable("outbox_messages", "identity", t =>
                        {
                            t.ExcludeFromMigrations();
                        });
                });

            modelBuilder.Entity("Vaulta.Catalog.Domain.Card", b =>
                {
                    b.HasOne("Vaulta.Catalog.Domain.Game", "Game")
                        .WithMany("Cards")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Vaulta.Catalog.Domain.Printing", b =>
                {
                    b.HasOne("Vaulta.Catalog.Domain.Card", "Card")
                        .WithMany("Printings")
                        .HasForeignKey("CardId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vaulta.Catalog.Domain.Set", "Set")
                        .WithMany("Printings")
                        .HasForeignKey("SetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Card");

                    b.Navigation("Set");
                });

            modelBuilder.Entity("Vaulta.Catalog.Domain.Series", b =>
                {
                    b.HasOne("Vaulta.Catalog.Domain.Game", "Game")
                        .WithMany("Series")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Game");
                });

            modelBuilder.Entity("Vaulta.Catalog.Domain.Set", b =>
                {
                    b.HasOne("Vaulta.Catalog.Domain.Game", "Game")
                        .WithMany("Sets")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Vaulta.Catalog.Domain.Series", "Series")
                        .WithMany("Sets")
                        .HasForeignKey("SeriesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Game");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("Vaulta.Catalog.Domain.Variant", b =>
                {
                    b.HasOne("Vaulta.Catalog.Domain.Printing", "Printing")
                        .WithMany("Variants")
                        .HasForeignKey("PrintingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Printing");
                });

            modelBuilder.Entity("Vaulta.Catalog.Infrastructure.DailyCardMarketSnapshot", b =>
                {
                    b.HasOne("Vaulta.Catalog.Domain.Printing", null)
                        .WithMany()
                        .HasForeignKey("PrintingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Vaulta.Catalog.Domain.Card", b =>
                {
                    b.Navigation("Printings");
                });

            modelBuilder.Entity("Vaulta.Catalog.Domain.Game", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Series");

                    b.Navigation("Sets");
                });

            modelBuilder.Entity("Vaulta.Catalog.Domain.Printing", b =>
                {
                    b.Navigation("Variants");
                });

            modelBuilder.Entity("Vaulta.Catalog.Domain.Series", b =>
                {
                    b.Navigation("Sets");
                });

            modelBuilder.Entity("Vaulta.Catalog.Domain.Set", b =>
                {
                    b.Navigation("Printings");
                });
#pragma warning restore 612, 618
        }
    }
}
