<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>87ea49ac-b77c-490e-96b9-d24eb6a1cd22</UserSecretsId>
    <DockerDefaultTargetOS>Linux</DockerDefaultTargetOS>
    <DockerfileContext>..\..</DockerfileContext>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../Modules/Vision/Vaulta.Vision.Infrastructure/Vaulta.Vision.Infrastructure.csproj" />
    <ProjectReference Include="../Modules/Identity/Vaulta.Identity.Infrastructure/Vaulta.Identity.Infrastructure.csproj" />
    <ProjectReference Include="../Modules/Catalog/Vaulta.Catalog.Infrastructure/Vaulta.Catalog.Infrastructure.csproj" />
    <ProjectReference Include="../Modules/Assets/Vaulta.Assets.Infrastructure/Vaulta.Assets.Infrastructure.csproj" />
    <ProjectReference Include="../Modules/Collection/Vaulta.Collection.Infrastructure/Vaulta.Collection.Infrastructure.csproj" />
    <ProjectReference Include="../Modules/Collection/Vaulta.Collection.Contracts/Vaulta.Collection.Contracts.csproj" />
    <ProjectReference Include="../Modules/Marketplace/Vaulta.Marketplace.Infrastructure/Vaulta.Marketplace.Infrastructure.csproj" />
    <ProjectReference Include="../Modules/Orders/Vaulta.Orders.Infrastructure/Vaulta.Orders.Infrastructure.csproj" />
    <ProjectReference Include="../Modules/Payments/Vaulta.Payments.Infrastructure/Vaulta.Payments.Infrastructure.csproj" />
    <ProjectReference Include="../Modules/Shipping/Vaulta.Shipping.Infrastructure/Vaulta.Shipping.Infrastructure.csproj" />
    <ProjectReference Include="../Modules/Reviews/Vaulta.Reviews.Infrastructure/Vaulta.Reviews.Infrastructure.csproj" />
    <ProjectReference Include="../Modules/Wallets/Vaulta.Wallets.Infrastructure/Vaulta.Wallets.Infrastructure.csproj" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.6">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="10.2.3" />
    <PackageReference Include="OpenTelemetry.Extensions.Hosting" Version="1.19.1" />
    <PackageReference Include="OpenTelemetry.Instrumentation.AspNetCore" Version="1.19.0" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.23.0" />
  </ItemGroup>

</Project>